# Generated by Django 4.1.7 on 2023-03-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_remove_tag_content_type_remove_tag_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='work',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='tag',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
