# Generated by Django 4.1.7 on 2023-03-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_article_tag_remove_audiobook_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
        migrations.AddField(
            model_name='tag',
            name='Article',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.article'),
        ),
        migrations.AddField(
            model_name='tag',
            name='audiobooks',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.audiobook'),
        ),
        migrations.AddField(
            model_name='tag',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.book'),
        ),
        migrations.AddField(
            model_name='tag',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.work'),
        ),
    ]
