# Generated by Django 4.1.7 on 2023-03-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_article_tag_audiobook_tag_book_tag_work_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='work',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tag'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tag'),
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tag'),
        ),
        migrations.AddField(
            model_name='work',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tag'),
        ),
    ]
