# Generated by Django 4.1.7 on 2023-03-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_article_tag_remove_audiobook_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tip',
            field=models.CharField(default='article', max_length=100),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='tip',
            field=models.CharField(default='audiobook', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='tip',
            field=models.CharField(default='book', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='tip',
            field=models.CharField(default='events', max_length=100),
        ),
        migrations.AddField(
            model_name='work',
            name='tip',
            field=models.CharField(default='works', max_length=100),
        ),
    ]
