# Generated by Django 4.1.7 on 2023-03-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_article_tip_audiobook_tip_book_tip_event_tip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tip',
            field=models.CharField(default='event', max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='tip',
            field=models.CharField(default='work', max_length=100),
        ),
    ]
