# Generated by Django 4.1.7 on 2023-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_event_tip_alter_work_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tip',
            field=models.CharField(default='wor', max_length=100),
        ),
    ]
