# Generated by Django 4.1.7 on 2023-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_work_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tip',
            field=models.CharField(default='work', max_length=100),
        ),
    ]
