# Generated by Django 4.1.7 on 2023-03-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_work_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='article', max_length=100),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='type',
            field=models.CharField(default='audiobook', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default='book', max_length=100),
        ),
        migrations.AddField(
            model_name='work',
            name='type',
            field=models.CharField(default='work', max_length=100),
        ),
    ]
