# Generated by Django 4.1.7 on 2023-04-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_article_title_alter_audiobook_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_video',
            field=models.FileField(blank=True, upload_to='events/'),
        ),
    ]
