# Generated by Django 4.1.7 on 2023-03-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_alter_rate_content_type_alter_rate_object_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
    ]
